[[pre_commit]]
name = "NoDoNotCommit"
cmd = ["iprecommit-no-forbidden-strings", "--paths"]

[[pre_commit]]
name = "NewlineAtEndOfFile"
cmd = ["iprecommit-newline-at-eof"]
autofix = true
fail_fast = true
fix_cmd = ["iprecommit-newline-at-eof", "--fix"]

[[pre_commit]]
name = "CommonTypos"
cmd = ["iprecommit-typos", "--paths"]

[[pre_commit]]
name = "PythonFormat"
cmd = [".venv/bin/black", "--check"]
filters = ["*.py"]
fix_cmd = [".venv/bin/black"]
autofix = true
fail_fast = true

[[pre_commit]]
name = "RustFormat"
cmd = ["rustfmt", "--check"]
filters = ["*.rs"]
fix_cmd = ["rustfmt"]
autofix = true
fail_fast = true

# commit-msg checks
[[commit_msg]]
name = "CommitMessageFormat"
cmd = ["iprecommit-commit-msg-format", "--max-line-length", "72"]

[[commit_msg]]
name = "CommitMessageTypos"
cmd = ["iprecommit-typos", "--paths"]

# pre-push checks (run on commit messages)
[[pre_push]]
name = "NoDoNotPush"
cmd = ["iprecommit-no-forbidden-strings", "--strings", "DO NOT PUSH", "--commits"]
